apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: kube-ops
      bitwardenServerSDKURL: https://bitwarden-sdk-server.kube-ops.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: kube-ops
        key: ca.crt
      organizationID: a3223df9-320f-476d-ae6c-b2ba00541773
      projectID: f9f974eb-d57d-4afb-a4c0-b2c8014a05d7